### PR TITLE
add capacitor v6 support

### PR DESCRIPTION
**Pull request by vbryan**

### CODE REVIEW

**Comment by EinfachHans** [comment]
Did you used capacitor's migration tool?

**Comment by EinfachHans** [comment]
Looks like you did not, only updating the versions in `package.json` is not enough.
Capacitor has a guide, including a migration: https://capacitorjs.com/docs/updating/plugins/6-0

This was on my list for today anyway, so i will release a new version later today

**Comment by vbryan** [comment]
@EinfachHans good day. I think I've created  PR by accident. 
I've just started to test your solution if it is compatible for requirements that I have for my application. Versions exchange was enough to make it run on Android. At the moment it is enough to continue my tests.

Thanks for your extension.

**Comment by EinfachHans** [comment]
@vbryan No problem. I officially released [V6.0.0](https://github.com/EinfachHans/capacitor-email-composer/releases/tag/V6.0.0) including capacitor 6 support 😊

Feel free to test and let me know if you encounter problems

**Pull request closed without merging**
